version: '3'
services:
  web:
    image: nginx
    container_name: your_finance_nginx
    restart: always
    volumes:
      - .:/app/
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
     - ${APP_PORT}:80
    depends_on:
     - php
    networks:
      local-network:
      public-network:
  php:
    build:
      context: ./docker/php/
    container_name: your_finance_dev
    working_dir: /app
    image: your_finance/php
    tty: true
    restart: always
    volumes:
      - .:/app/
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
        - local-network
  db:
    image: mariadb
    restart: always
    container_name: your_finance_db
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - local-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
     - /sessions
    networks: 
      local-network:
      public-network: 
networks:
  local-network:
  public-network:
  
volumes:
  dbdata: