version: '3'
services:
  web:
    image: nginx
    container_name: your_finance_nginx
    restart: always
    volumes:
      - .:/app/
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
     - ${APP_PORT}:80
    depends_on:
     - php
    networks:
      local-network:
      public-network:
  php:
    build:
      context: ./docker/php/
    container_name: your_finance_dev
    working_dir: /app
    image: your_finance/php
    tty: true
    restart: always
    volumes:
      - .:/app/
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
        - local-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "16543:80"
    volumes:
      - pgadmindata_your_finance:/var/lib/pgadmin
    networks:
      - local-network
      - public-network
  postgresql_db:
    image: postgres
    restart: always
    container_name: your_finance_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - your_finance_data:/var/lib/postgresql/data
    networks:
      - local-network
networks:
  local-network:
  public-network:
  
volumes:
  pgadmindata_your_finance:
  your_finance_data: